-- Müller App · Supabase (plan gratuito)
-- Ejecuta esto en SQL Editor.
-- Si ya tenías versión anterior, este script amplía con economía segura por RPC.

-- ------------------------------
-- Perfiles
-- ------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users on delete cascade,
  display_name text,
  updated_at timestamptz default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_all" on public.profiles;
create policy "profiles_select_all"
  on public.profiles for select
  using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles for insert
  with check ((select auth.uid()) = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  using ((select auth.uid()) = id);

create or replace function public.muller_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, updated_at)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'display_name', 'Estudiante'),
    now()
  )
  on conflict (id) do update
    set display_name = excluded.display_name,
        updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.muller_handle_new_user();

-- ------------------------------
-- Liga semanal
-- ------------------------------
create table if not exists public.league_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  week_key text not null,
  score int not null default 0,
  display_name text,
  updated_at timestamptz default now(),
  unique (user_id, week_key)
);

create index if not exists league_scores_week_score_idx
  on public.league_scores (week_key, score desc);

alter table public.league_scores enable row level security;

drop policy if exists "league_select_all" on public.league_scores;
create policy "league_select_all"
  on public.league_scores for select
  using (true);

drop policy if exists "league_insert_own" on public.league_scores;
create policy "league_insert_own"
  on public.league_scores for insert
  with check ((select auth.uid()) = user_id);

drop policy if exists "league_update_own" on public.league_scores;
create policy "league_update_own"
  on public.league_scores for update
  using ((select auth.uid()) = user_id);

-- ------------------------------
-- Estado app sincronizable (multi-dispositivo)
-- ------------------------------
create table if not exists public.muller_user_state (
  user_id uuid primary key references auth.users on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.muller_user_state enable row level security;

drop policy if exists "muller_user_state_select_own" on public.muller_user_state;
create policy "muller_user_state_select_own"
  on public.muller_user_state for select
  using ((select auth.uid()) = user_id);

drop policy if exists "muller_user_state_insert_own" on public.muller_user_state;
create policy "muller_user_state_insert_own"
  on public.muller_user_state for insert
  with check ((select auth.uid()) = user_id);

drop policy if exists "muller_user_state_update_own" on public.muller_user_state;
create policy "muller_user_state_update_own"
  on public.muller_user_state for update
  using ((select auth.uid()) = user_id);

-- ------------------------------
-- Economía segura (anti-trampa base)
-- ------------------------------
create table if not exists public.muller_wallets (
  user_id uuid primary key references auth.users on delete cascade,
  coins bigint not null default 0,
  updated_at timestamptz default now()
);

create table if not exists public.muller_reward_claims (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  reward_type text not null,
  day_key text not null,
  claim_count int not null default 1,
  last_claim_at timestamptz not null default now(),
  unique (user_id, reward_type, day_key)
);

create index if not exists muller_reward_claims_user_day_idx
  on public.muller_reward_claims (user_id, day_key);

-- Lista de creadores con ventajas (solo SQL manual / service role)
create table if not exists public.muller_creator_accounts (
  user_id uuid primary key references auth.users on delete cascade,
  note text,
  created_at timestamptz default now()
);

alter table public.muller_wallets enable row level security;
alter table public.muller_reward_claims enable row level security;
alter table public.muller_creator_accounts enable row level security;

drop policy if exists "wallet_select_own" on public.muller_wallets;
create policy "wallet_select_own"
  on public.muller_wallets for select
  using ((select auth.uid()) = user_id);

drop policy if exists "claims_select_own" on public.muller_reward_claims;
create policy "claims_select_own"
  on public.muller_reward_claims for select
  using ((select auth.uid()) = user_id);

drop policy if exists "creator_select_own" on public.muller_creator_accounts;
create policy "creator_select_own"
  on public.muller_creator_accounts for select
  using ((select auth.uid()) = user_id);

create or replace function public.muller_is_creator(p_user uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists(select 1 from public.muller_creator_accounts c where c.user_id = p_user);
$$;

create or replace function public.muller_get_wallet()
returns table (coins bigint, is_creator boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid;
begin
  v_uid := auth.uid();
  if v_uid is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  insert into public.muller_wallets (user_id, coins, updated_at)
  values (v_uid, 0, now())
  on conflict (user_id) do nothing;

  return query
    select
      case
        when public.muller_is_creator(v_uid) then 999999999::bigint
        else coalesce((select w.coins from public.muller_wallets w where w.user_id = v_uid), 0)::bigint
      end as coins,
      public.muller_is_creator(v_uid) as is_creator;
end;
$$;

-- Sin SELECT/RETURNING ... INTO: usar asignaciones := (subconsulta) para evitar 42P01 con nombres de salida.
create or replace function public.muller_claim_reward(p_reward_type text)
returns table (granted int, balance bigint, reason text)
language plpgsql
security definer
set search_path = public
as $claim$
declare
  v_uid uuid;
  v_day text := to_char(now(), 'YYYY-MM-DD');
  v_now timestamptz := now();
  v_claims_today int := 0;
  v_last_claim timestamptz := null;
  v_granted int := 0;
  v_bal bigint := 0;
  v_reason text := 'ok';
begin
  v_uid := auth.uid();
  if v_uid is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  insert into public.muller_wallets (user_id, coins, updated_at)
  values (v_uid, 0, now())
  on conflict (user_id) do nothing;

  if public.muller_is_creator(v_uid) then
    granted := 0;
    balance := 999999999::bigint;
    reason := 'creator_unlimited';
    return next;
    return;
  end if;

  if p_reward_type not in ('daily_bonus', 'ad_reward') then
    v_bal := coalesce((
      select coins::bigint from public.muller_wallets where user_id = v_uid
    ), 0);
    granted := 0;
    balance := v_bal;
    reason := 'invalid_reward_type';
    return next;
    return;
  end if;

  v_claims_today := coalesce((
    select claim_count from public.muller_reward_claims
    where user_id = v_uid and reward_type = p_reward_type and day_key = v_day
  ), 0);
  v_last_claim := (
    select last_claim_at from public.muller_reward_claims
    where user_id = v_uid and reward_type = p_reward_type and day_key = v_day
  );

  v_granted := 0;
  v_reason := 'ok';

  if p_reward_type = 'daily_bonus' then
    if v_claims_today >= 1 then
      v_reason := 'already_claimed_today';
    else
      v_granted := 40;
    end if;
  elsif p_reward_type = 'ad_reward' then
    if v_claims_today >= 6 then
      v_reason := 'daily_limit_reached';
    elsif v_last_claim is not null and v_last_claim > (v_now - interval '15 minutes') then
      v_reason := 'cooldown_15m';
    else
      v_granted := 18;
    end if;
  end if;

  if v_granted > 0 then
    update public.muller_wallets
      set coins = coins + v_granted,
          updated_at = v_now
      where user_id = v_uid;
    v_bal := coalesce((
      select coins::bigint from public.muller_wallets where user_id = v_uid
    ), 0);

    insert into public.muller_reward_claims (user_id, reward_type, day_key, claim_count, last_claim_at)
    values (v_uid, p_reward_type, v_day, 1, v_now)
    on conflict (user_id, reward_type, day_key)
    do update set claim_count = public.muller_reward_claims.claim_count + 1,
                  last_claim_at = excluded.last_claim_at;
    v_reason := 'ok';
  else
    v_bal := coalesce((
      select coins::bigint from public.muller_wallets where user_id = v_uid
    ), 0);
  end if;

  granted := v_granted;
  balance := coalesce(v_bal, 0);
  reason := v_reason;
  return next;
end;
$claim$;

create or replace function public.muller_spend_coins(p_amount int, p_reason text default 'spend')
returns table (ok boolean, balance bigint, reason text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid;
  v_is_creator boolean := false;
  v_balance bigint := 0;
begin
  v_uid := auth.uid();
  if v_uid is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  if p_amount is null or p_amount <= 0 then
    return query select false, 0::bigint, 'invalid_amount';
    return;
  end if;

  insert into public.muller_wallets (user_id, coins, updated_at)
  values (v_uid, 0, now())
  on conflict (user_id) do nothing;

  v_is_creator := public.muller_is_creator(v_uid);
  if v_is_creator then
    return query select true, 999999999::bigint, 'creator_unlimited';
    return;
  end if;

  update public.muller_wallets
    set coins = coins - p_amount,
        updated_at = now()
    where user_id = v_uid
      and coins >= p_amount
    returning coins into v_balance;

  if v_balance is null then
    select coins into v_balance from public.muller_wallets where user_id = v_uid;
    return query select false, coalesce(v_balance, 0), 'insufficient_coins';
    return;
  end if;

  return query select true, v_balance, coalesce(p_reason, 'ok');
end;
$$;

create or replace function public.muller_submit_league_score(p_week_key text, p_score int, p_display_name text)
returns table (saved_score int)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid;
  v_score int;
begin
  v_uid := auth.uid();
  if v_uid is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  v_score := greatest(0, least(coalesce(p_score, 0), 50000));

  insert into public.league_scores (user_id, week_key, score, display_name, updated_at)
  values (v_uid, coalesce(p_week_key, to_char(now(), 'YYYY-MM-DD')), v_score, left(coalesce(p_display_name, 'Estudiante'), 80), now())
  on conflict (user_id, week_key)
  do update set score = greatest(public.league_scores.score, excluded.score),
                display_name = excluded.display_name,
                updated_at = now();

  return query
    select score from public.league_scores where user_id = v_uid and week_key = coalesce(p_week_key, to_char(now(), 'YYYY-MM-DD'));
end;
$$;

-- ------------------------------
-- Estado de recompensas (UI)
-- ------------------------------
create or replace function public.muller_reward_status()
returns table (
  day_key text,
  daily_bonus_claimed boolean,
  ad_claims_today int,
  ad_remaining_today int,
  ad_cooldown_seconds int
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid;
  v_day text := to_char(now(), 'YYYY-MM-DD');
  v_ad_claims int := 0;
  v_daily_claims int := 0;
  v_last_ad timestamptz := null;
  v_cd int := 0;
begin
  v_uid := auth.uid();
  if v_uid is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  select claim_count, last_claim_at
    into v_ad_claims, v_last_ad
    from public.muller_reward_claims
    where user_id = v_uid and reward_type = 'ad_reward' and day_key = v_day;
  v_ad_claims := coalesce(v_ad_claims, 0);

  select claim_count
    into v_daily_claims
    from public.muller_reward_claims
    where user_id = v_uid and reward_type = 'daily_bonus' and day_key = v_day;
  v_daily_claims := coalesce(v_daily_claims, 0);

  if v_last_ad is not null and v_last_ad > (now() - interval '15 minutes') then
    v_cd := greatest(0, ceil(extract(epoch from ((v_last_ad + interval '15 minutes') - now())))::int);
  else
    v_cd := 0;
  end if;

  return query
    select
      v_day,
      (v_daily_claims >= 1),
      v_ad_claims,
      greatest(0, 6 - v_ad_claims),
      v_cd;
end;
$$;

-- ------------------------------
-- Premium mensual (modo simple)
-- ------------------------------
create table if not exists public.muller_premium_subscriptions (
  user_id uuid primary key references auth.users on delete cascade,
  plan text not null default 'monthly',
  status text not null default 'inactive',
  started_at timestamptz,
  expires_at timestamptz,
  payment_ref text,
  updated_at timestamptz default now()
);

alter table public.muller_premium_subscriptions enable row level security;

drop policy if exists "premium_select_own" on public.muller_premium_subscriptions;
create policy "premium_select_own"
  on public.muller_premium_subscriptions for select
  using ((select auth.uid()) = user_id);

drop policy if exists "premium_insert_own" on public.muller_premium_subscriptions;
create policy "premium_insert_own"
  on public.muller_premium_subscriptions for insert
  with check ((select auth.uid()) = user_id);

drop policy if exists "premium_update_own" on public.muller_premium_subscriptions;
create policy "premium_update_own"
  on public.muller_premium_subscriptions for update
  using ((select auth.uid()) = user_id);

create or replace function public.muller_get_premium_status()
returns table (status text, plan text, expires_at timestamptz, is_active boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid;
begin
  v_uid := auth.uid();
  if v_uid is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  insert into public.muller_premium_subscriptions (user_id, plan, status, updated_at)
  values (v_uid, 'monthly', 'inactive', now())
  on conflict (user_id) do nothing;

  return query
    select
      s.status,
      s.plan,
      s.expires_at,
      (s.status = 'active' and s.expires_at is not null and s.expires_at > now()) as is_active
    from public.muller_premium_subscriptions s
    where s.user_id = v_uid;
end;
$$;
-- Müller App · Supabase (plan gratuito)
-- Ejecuta esto en: SQL Editor → New query → Run
-- Auth: Authentication → Providers → Email → puedes desactivar "Confirm email" para pruebas locales.

-- Perfiles públicos (lectura para todos los usuarios autenticados / anon según políticas)
create table if not exists public.profiles (
  id uuid primary key references auth.users on delete cascade,
  display_name text,
  updated_at timestamptz default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_all" on public.profiles;
create policy "profiles_select_all"
  on public.profiles for select
  using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles for insert
  with check ((select auth.uid()) = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  using ((select auth.uid()) = id);

-- Perfil al registrarse (metadata display_name desde la app)
create or replace function public.muller_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, updated_at)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'display_name', 'Estudiante'),
    now()
  )
  on conflict (id) do update
    set display_name = excluded.display_name,
        updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.muller_handle_new_user();

-- Liga semanal: una fila por usuario y semana (week_key = lunes ISO YYYY-MM-DD)
create table if not exists public.league_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  week_key text not null,
  score int not null default 0,
  display_name text,
  updated_at timestamptz default now(),
  unique (user_id, week_key)
);

create index if not exists league_scores_week_score_idx
  on public.league_scores (week_key, score desc);

alter table public.league_scores enable row level security;

drop policy if exists "league_select_all" on public.league_scores;
create policy "league_select_all"
  on public.league_scores for select
  using (true);

drop policy if exists "league_insert_own" on public.league_scores;
create policy "league_insert_own"
  on public.league_scores for insert
  with check ((select auth.uid()) = user_id);

drop policy if exists "league_update_own" on public.league_scores;
create policy "league_update_own"
  on public.league_scores for update
  using ((select auth.uid()) = user_id);
