var TEMPUS_DICT = {
            "ausstellen": "Prät: stellte aus | Perf: hat ausgestellt",
            "bekommen": "Prät: bekam | Perf: hat bekommen",
            "entstehen": "Prät: entstand | Perf: ist entstanden",
            "entstanden": "Prät: entstand | Perf: ist entstanden",
            "sehen": "Prät: sah | Perf: hat gesehen",
            "sieht": "Prät: sah | Perf: hat gesehen",
            "geboren": "Prät: wurde geboren | Perf: ist geboren worden",
            "fliehen": "Prät: floh | Perf: ist geflohen",
            "kämpfen": "Prät: kämpfte | Perf: hat gekämpft",
            "anerkennen": "Prät: erkannte an | Perf: hat anerkannt",
            "stehlen": "Prät: stahl | Perf: hat gestohlen",
            "gestohlen": "Prät: stahl | Perf: hat gestohlen",
            "verhaften": "Prät: verhaftete | Perf: hat verhaftet",
            "sterben": "Prät: starb | Perf: ist gestorben",
            "gestorben": "Prät: starb | Perf: ist gestorben",
            "einsetzen": "Prät: setzte ein | Perf: hat eingesetzt",
            "essen": "Prät: aß | Perf: hat gegessen",
            "trinken": "Prät: trank | Perf: hat getrunken",
            "fahren": "Prät: fuhr | Perf: ist gefahren",
            "gehen": "Prät: ging | Perf: ist gegangen",
            "kommen": "Prät: kam | Perf: ist gekommen",
            "sprechen": "Prät: sprach | Perf: hat gesprochen",
            "nehmen": "Prät: nahm | Perf: hat genommen",
            "geben": "Prät: gab | Perf: hat gegeben",
            "helfen": "Prät: half | Perf: hat geholfen",
            "laufen": "Prät: lief | Perf: ist gelaufen",
            "schlafen": "Prät: schlief | Perf: hat geschlafen",
            "treffen": "Prät: traf | Perf: hat getroffen",
            "finden": "Prät: fand | Perf: hat gefunden",
            "bleiben": "Prät: blieb | Perf: ist geblieben",
            "tragen": "Prät: trug | Perf: hat getragen",
            "waschen": "Prät: wusch | Perf: hat gewaschen",
            "verlieren": "Prät: verlor | Perf: hat verloren",
            "schreiben": "Prät: schrieb | Perf: hat geschrieben",
            "lesen": "Prät: las | Perf: hat gelesen",
            "wissen": "Prät: wusste | Perf: hat gewusst",
            "denken": "Prät: dachte | Perf: hat gedacht",
            "bringen": "Prät: brachte | Perf: hat gebracht",
            "kennen": "Prät: kannte | Perf: hat gekannt",
            "nennen": "Prät: nannte | Perf: hat genannt"
        };

